import mitt from 'mitt'

export const bus = mitt()

export const EVENT_NAMES = {
  SEND_MESSAGE: 'SEND_MESSAGE',
  MESSAGE_COMPLETE: 'MESSAGE_COMPLETE',
  AI_AUTO_RENAME: 'AI_AUTO_RENAME',
  CLEAR_MESSAGES: 'CLEAR_MESSAGES',
  ADD_ASSISTANT: 'ADD_ASSISTANT',
  EDIT_MESSAGE: 'EDIT_MESSAGE',
  REGENERATE_MESSAGE: 'REGENERATE_MESSAGE',
  CHAT_COMPLETION_PAUSED: 'CHAT_COMPLETION_PAUSED',
  ESTIMATED_TOKEN_COUNT: 'ESTIMATED_TOKEN_COUNT',
  SHOW_ASSISTANTS: 'SHOW_ASSISTANTS',
  SHOW_CHAT_SETTINGS: 'SHOW_CHAT_SETTINGS',
  SHOW_TOPIC_SIDEBAR: 'SHOW_TOPIC_SIDEBAR',
  SWITCH_TOPIC_SIDEBAR: 'SWITCH_TOPIC_SIDEBAR',
  SWITCH_ASSISTANT: 'SWITCH_ASSISTANT',
  NEW_CONTEXT: 'NEW_CONTEXT',
  NEW_BRANCH: 'NEW_BRANCH',
  COPY_TOPIC_IMAGE: 'COPY_TOPIC_IMAGE',
  EXPORT_TOPIC_IMAGE: 'EXPORT_TOPIC_IMAGE',
  LOCATE_MESSAGE: 'LOCATE_MESSAGE',
  ADD_NEW_TOPIC: 'ADD_NEW_TOPIC',
  RESEND_MESSAGE: 'RESEND_MESSAGE',
  SHOW_MODEL_SELECTOR: 'SHOW_MODEL_SELECTOR',
  EDIT_CODE_BLOCK: 'EDIT_CODE_BLOCK',
  CHANGE_TOPIC: 'CHANGE_TOPIC',
  OPEN_SHORTCUTS: 'OPEN_SHORTCUTS',
  OPEN_SEARCH_POPUP: 'OPEN_SEARCH_POPUP',
  SEARCH_IN_CHAT: 'SEARCH_IN_CHAT',
  NEXT_SEARCH_MATCH: 'NEXT_SEARCH_MATCH',
  PREV_SEARCH_MATCH: 'PREV_SEARCH_MATCH',
  START_GENERATING: 'START_GENERATING',
  STOP_GENERATING: 'STOP_GENERATING'
  ,
  STOP_GENERATING_MESSAGE: 'STOP_GENERATING_MESSAGE'
  ,
  SCROLL_TO_BOTTOM: 'SCROLL_TO_BOTTOM',
  SCROLL_TO_TOP: 'SCROLL_TO_TOP',
  MULTI_SELECT_ON: 'MULTI_SELECT_ON',
  MULTI_SELECT_OFF: 'MULTI_SELECT_OFF',
  SEND_MESSAGE_AGAIN: 'SEND_MESSAGE_AGAIN',
  CONTINUE_CONVERSATION: 'CONTINUE_CONVERSATION'
  ,
  FOCUS_INPUT: 'FOCUS_INPUT'
  ,
  APPEND_TO_INPUT: 'APPEND_TO_INPUT'
  ,
  MULTI_SELECT_SELECT_ALL: 'MULTI_SELECT_SELECT_ALL',
  MULTI_SELECT_INVERT: 'MULTI_SELECT_INVERT',
  MULTI_SELECT_BATCH_DELETE: 'MULTI_SELECT_BATCH_DELETE',
  MULTI_SELECT_BATCH_COPY: 'MULTI_SELECT_BATCH_COPY',
  MULTI_SELECT_BATCH_COPY_TO_INPUT: 'MULTI_SELECT_BATCH_COPY_TO_INPUT',
  MULTI_SELECT_EXPORT_MD: 'MULTI_SELECT_EXPORT_MD'
  ,
  MULTI_SELECT_EXPORT_MD_FILE: 'MULTI_SELECT_EXPORT_MD_FILE'
}


